from enum import IntEnum


class LoginCommandCode(IntEnum):
    WELCOME_NOTIFY = 16
    LOGIN_REQ = 17
    LOGIN_ANSWER = 18
    LOGOUT_REQ = 19
    LOGOUT_ANSWER = 20
    SERVER_LIST_REQ = 23
    SERVER_LIST_ANSWER = 24
    REGISTER_REQ = 33
    REGISTER_ANSWER = 34


class WorldCommandCode(IntEnum):
    WORLD_LOGIN_REQ = 33
    WORLD_LOGIN_ANSWER = 34
    WORLD_LOGOUT_REQ = 35
    WORLD_LOGOUT_ANSWER = 36
    WORLD_PING_ECHO = 49
    WORLD_CLIENT_SAVE_CONFIG_REQ = 50
    WORLD_CLIENT_SAVE_CONFIG_NOTIFY = 50
    WORLD_TIME_CHECK_NOTIFY = 51
    SYS_VAR_CHANGE_NOTIFY = 65
    SYS_VAR_CLEAR_NOTIFY = 66
    WORLD_PVE_MAPS_REQ = 81
    WORLD_PVE_MAPS_ANSWER = 82
    PVE_MAPS_REQ = 81
    PVE_MAPS_ANSWER = 82


class RoleCommandCode(IntEnum):
    ROLE_LIST_REQ = 257
    ROLE_LIST_ANSWER = 258
    ROLE_NAME_CONFIRM_REQ = 259
    ROLE_NAME_CONFIRM_ANSWER = 260
    CREATE_ROLE_REQ = 261
    CREATE_ROLE_ANSWER = 262
    DELETE_ROLE_REQ = 263
    DELETE_ROLE_ANSWER = 264
    SELECT_ROLE_REQ = 265
    SELECT_ROLE_ANSWER = 272
    RECOVER_ROLE_REQ = 273
    RECOVER_ROLE_ANSWER = 274
    SET_ROLE_PW_REQ = 275
    SET_ROLE_PW_ANSWER = 276


class PlayerCommandCode(IntEnum):
    PLAYER_ENTER_WORLD_REQ = 513
    PLAYER_ENTER_WORLD_ANSWER = 514
    PLAYER_LEAVE_WORLD_REQ = 515
    PLAYER_LEAVE_WORLD_ANSWER = 516
    PLAYER_ENTER_MAP_REQ = 517
    PLAYER_ENTER_MAP_ANSWER = 518
    PLAYER_MOVE_REQ = 519
    PLAYER_POSITION_CHECK_NOTIFY = 520
    PLAYER_VIEW_MAP_REQ = 521
    PLAYER_VIEW_MAP_ANSWER = 522
    PLAYER_SELECT_LINE_REQ = 523
    PLAYER_USE_SKILL_REQ = 545
    PLAYER_LUCKY_SKILL_NOTIFY = 547
    PLAYER_CANCEL_SKILL_REQ = 548
    PLAYER_SKILL_INTERRUPTED_NOTIFY = 549
    PLAYER_HP_CHANGE_NOTIFY = 550
    PLAYER_HPMAX_CHANGE_NOTIFY = 551
    PLAYER_MP_CHANGE_NOTIFY = 552
    PLAYER_MPMAX_CHANGE_NOTIFY = 553
    PLAYER_BUFF_CHANGE_NOTIFY = 560
    PLAYER_EXP_CHANGE_NOTIFY = 561
    PLAYER_LEVEL_UP_NOTIFY = 562
    PLAYER_GOLD_CHANGE_NOTIFY = 563
    PLAYER_MONEY_CHANGE_NOTIFY = 564
    PLAYER_DIED_NOTIFY = 565
    PLAYER_REBIRTH_REQUEST = 567
    PLAYER_REBIRTH_NOTIFY = 568
    PLAYER_COMBAT_STATUS_CHECK_NOTIFY = 570
    PLAYER_SIT_REQUEST = 583
    PLAYER_SIT_CHECK_NOTIFY = 584
    PLAYER_ATTRIBUTES_CHANGE_NOTIFY = 578
    PLAYER_EXT_ATTR_INT_CHANGE_NOTIFY = 689
    PLAYER_ASSIGN_ATTR_REQUEST = 690
    PLAYER_SEND_MSG_REQUEST = 673
    PLAYER_RECEIVE_MSG_NOTIFY = 674
    PLAYER_RECEIVE_SYS_PROMPT_NOTIFY = 675
    PLAYER_SHOW_TALKS_NOTIFY = 676


class BagCommandCode(IntEnum):
    PLAYER_BAG_CHECK_NOTIFY = 5121
    PLAYER_BAG_CAPACITY_CHANGE_NOTIFY = 5122
    PLAYER_PICKUP_ITEM_REQ = 5123
    PLAYER_USE_ITEM_REQ = 5124
    PLAYER_ITEM_USED_NOTIFY = 5130
    PLAYER_MOVE_ITEM_REQ = 5125
    PLAYER_SPLIT_ITEM_REQ = 5126
    PLAYER_DROP_ITEM_REQ = 5127
    PLAYER_MOVE_ITEM_CROSS_BAG_REQ = 5128
    PLAYER_VIEW_BAG_REQ = 5129
    PLAYER_ITEM_ADDED_NOTIFY = 5131
    PLAYER_ITEM_CD_CHECK_NOTIFY = 5132
    PLAYER_VIEW_ITEM_REQ = 5133
    PLAYER_VIEW_ITEM_ANSWER = 5134
    PLAYER_RENEW_ITEM_REQ = 5137
    PLAYER_BUY_AND_USE_ITEM_REQ = 5138
    PLAYER_BAG_SORT_REQ = 5141


class TradeCommandCode(IntEnum):
    PLAYER_INVITE_TRADE_REQUEST = 2897
    PLAYER_RECEIVE_INVITE_TRADE_REQUEST_NOTIFY = 2898
    PLAYER_PROCESS_INVITE_TRADE_REQUEST_REPLY = 2899
    PLAYER_INVITE_TRADE_ANSWER = 2900
    PLAYER_TRADE_BEGIN_NOTIFY = 2913
    PLAYER_TRADE_ITEM_SUBMIT_REQUEST = 2914
    PLAYER_TRADE_ITEM_SUBMIT_NOTIFY = 2915
    PLAYER_TRADE_CONFIRM_REQUEST = 2916
    PLAYER_TRADE_CONFIRM_NOTIFY = 2917
    PLAYER_TRADE_CANCEL_REQUEST = 2918
    PLAYER_TRADE_END_NOTIFY = 2919
    PLAYER_TRADE_CHECK_REQUEST = 2920
    PLAYER_TRADE_CHECK_ANSWER = 2921


class BoothCommandCode(IntEnum):
    BOOTH_CHECK_NOTIFY = 2945
    BOOTH_START_REQUEST = 2946
    BOOTH_STOP_REQUEST = 2947
    BOOTH_SET_TITLE_REQUEST = 2948
    BOOTH_VISIT_REQUEST = 2949
    BOOTH_VISIT_ANSWER = 2950
    BOOTH_BUY_ITEM_REQUEST = 2951
    BOOTH_ITEM_SOLD_NOTIFY = 2952
    BOOTH_PURCHASE_ITEM_REQUEST = 2953
    BOOTH_ITEM_PURCHASED_NOTIFY = 2954


class MapCommandCode(IntEnum):
    MAP_ITEM_ADDED_NOTIFY = 1537
    MAP_ITEM_REMOVED_NOTIFY = 1538
    MAP_TELEPORT_REQUEST = 1539
    FARM_TELEPORT_REQUEST = 1540
    MAP_VAR_CHANGE_NOTIFY = 1541
    MAP_VAR_CLEAR_NOTIFY = 1542
    MAP_REFRESH_NOTIFY = 1543
    MAP_NPC_SAY_NOTIFY = 1544
    MAP_DAMAGE_VALUE_CHECK_NOTIFY = 1601
    MAP_DAMAGE_RANK_CHECK_NOTIFY = 1602
    MAP_HARVEST_COLLECT_REQUEST = 1610
    MAP_HARVEST_COLLECT_ANSWER = 1611
    MAP_HARVEST_NODES_NOTIFY = 1612


class EquipmentCommandCode(IntEnum):
    PLAYER_REMOVE_EQUIPMENT_REQ = 4610
    PLAYER_EQUIPMENT_CHECK_NOTIFY = 4609
    PLAYER_SWITCH_FASHION_REQUEST = 4611
    PLAYER_SWITCH_FASHION_NOTIFY = 4612
    PLAYER_EQUIP_DUR_CHECK_NOTIFY = 4613
    PLAYER_VIEW_REPAIR_INFO_REQUEST = 4618
    PLAYER_VIEW_REPAIR_INFO_ANSWER = 4619
    PLAYER_REPAIR_EQUIPMENT_REQUEST = 4620
    PLAYER_REPAIR_EQUIPMENT_ANSWER = 4621


class ArmoryCommandCode(IntEnum):
    PLAYER_ARMORY_REMOVE_REQUEST = 4625
    PLAYER_ARMORY_PROPERTY_NOTIFY = 4626
    PLAYER_ARMORY_UPGRADE_REQUEST = 4627
    PLAYER_ARMORY_UPGRADE_ANSWER = 4628
    PLAYER_ARMORY_UPGRADE_NOTIFY = 4629


class ArtifactCommandCode(IntEnum):
    ARTIFACT_HOLE_REQUEST = 6145
    ARTIFACT_HOLE_ANSWER = 6146
    ARTIFACT_EMBED_REQUEST = 6147
    ARTIFACT_EMBED_ANSWER = 6148
    ARTIFACT_DISEMBED_REQUEST = 6149
    ARTIFACT_DISEMBED_ANSWER = 6150
    ARTIFACT_REFINE_REQUEST = 6161
    ARTIFACT_REFINE_ANSWER = 6162
    ARTIFACT_SOUL_REQUEST = 6165
    ARTIFACT_SOUL_ANSWER = 6166
    ARTIFACT_SOUL_MOVE_REQUEST = 6167
    ARTIFACT_SOUL_MOVE_ANSWER = 6168
    ARTIFACT_DECOMPOSE_REQUEST = 6177
    ARTIFACT_UPGRADE_REQUEST = 6181
    ARTIFACT_UPGRADE_ANSWER = 6182
    ARTIFACT_FUSION_REQUEST = 6183
    ARTIFACT_FUSION_ANSWER = 6184
    ARTIFACT_WASH_REQUEST = 6192
    ARTIFACT_WASH_ANSWER = 6193
    ARTIFACT_HOLESKILL_REQUEST = 6194
    ARTIFACT_HOLESKILL_ANSWER = 6195
    ARTIFACT_HOST_REQUEST = 6196
    ARTIFACT_HOST_ANSWER = 6197
    ARTIFACT_CLEAN_SKILL_REQUEST = 6198
    ARTIFACT_CLEAN_SKILL_ANSWER = 6199
    ARTIFACT_LETTERING_REQUEST = 6200
    ARTIFACT_LETTERING_ANSWER = 6201
    ARTIFACT_UP_EQU_EXP_REQUEST = 6208
    ARTIFACT_UP_EQU_EXP_ANSWER = 6209


class WardrobeCommandCode(IntEnum):
    WARDROBE_ADD_REQUEST = 8293
    WARDROBE_REMOVE_REQUEST = 8294
    WARDROBE_UPLEVEL_REQUEST = 8295
    WARDROBE_UPLEVEL_ANSWER = 8296
    WARDROBE_ITEMS_NOTIFY = 8297


class EquipKindGrowCommandCode(IntEnum):
    KIND_GROW_ADD_EXP_REQUEST = 10800
    KIND_GROW_ADD_EXP_ANSWER = 10801
    KIND_GROW_BREACH_REQUEST = 10802
    KIND_GROW_BREACH_ANSWER = 10803
    KIND_GROW_BLESS_REQUEST = 10804
    KIND_GROW_BLESS_ANSWER = 10805
    KIND_GROW_TEMPER_REQUEST = 10806
    KIND_GROW_TEMPER_ANSWER = 10807
    KIND_GROW_TEMPER_SAVE_REQUEST = 10808
    KIND_GROW_TEMPER_SAVE_ANSWER = 10809
    KIND_GROW_INFO_NOTIFY = 10810


class AgentCommandCode(IntEnum):
    AGENT_SELL_ITEM_REQUEST = 2865
    AGENT_CANCEL_ITEM_REQUEST = 2866
    AGENT_BUY_ITEM_REQUEST = 2867
    AGENT_LIST_ITEM_REQUEST = 2868
    AGENT_LIST_ITEM_ANSWER = 2869
    AGENT_VIEW_MY_ITEMS_REQUEST = 2870
    AGENT_VIEW_MY_ITEMS_ANSWER = 2871
    AGENT_TAKE_BACK_REQUEST = 2872


class PetCommandCode(IntEnum):
    PET_CHECK_NOTIFY = 5377
    PET_VIEW_REQUEST = 5378
    PET_ATTR_INT_CHANGE_NOTIFY = 5379
    PET_RENAME_REQUEST = 5380
    PET_FORGET_SKILL_REQUEST = 5381
    PET_ASSIGN_ATTR_REQUEST = 5382
    PET_LEARN_SKILL_REQUEST = 5383
    PET_LEARN_SKILL_ANSWER = 5384
    PET_USE_SKILL_NOTIFY = 5409
    PET_HP_CHANGE_NOTIFY = 5410
    PLAYER_SET_PET_ACTION_MODE_REQUEST = 5411
    PLAYER_PET_ACTION_MODE_CHANGE_NOTIFY = 5412
    PET_ENHANCE_REQUEST = 5413
    PET_ENHANCE_ANSWER = 5414
    PET_FUSION_REQUEST = 5415
    PET_FUSION_ANSWER = 5416
    PET_REMOVE_EQUIPMENT_REQUEST = 5424
    PET_DECOMPOSE_REQUEST = 5431


class ShopCommandCode(IntEnum):
    SHOP_SELL_ITEM_REQ = 2817
    SHOP_BUY_ITEM_REQ = 2818
    STORE_BUY_ITEM_REQ = 2819
    LEAD_ITEM_INFO_NOTIFY = 2820
    LEAD_ITEM_INFO_REQ = 2821
    LEAD_BUY_ITEM_REQ = 2822
    VIP_SHOP_BUY_ITEM_REQ = 2823
    SHOP_BUY_ITEM_ANSWER = 2824
    SHOP_SELL_ITEM_ANSWER = 2825
    VIP_SHOP_BUY_ITEM_ANSWER = 2824
    REWARD_SHOP_BUY_REQ = 10557
    REWARD_SHOP_BUY_ANSWER = 10558
    VAR_SHOP_BUY_REQ = 10560
    VAR_SHOP_BUY_ANSWER = 10561


class NpcCommandCode(IntEnum):
    NPC_FUNCTION_REQUEST = 1025
    NPC_FUNCTION_ANSWER = 1029
    NPC_ASSEMBLE_ITEM_REQUEST = 1026
    NPC_ASSEMBLE_ITEM_ANSWER = 1027


class WingSpiritCommandCode(IntEnum):
    PLAYER_WING_SPIRIT_REQUEST = 12544
    PLAYER_WING_SPIRIT_ANSWER = 12545


class PvPCommandCode(IntEnum):
    PLAYER_SET_PK_MODE_REQUEST = 641
    PLAYER_PK_MODE_CHANGE_NOTIFY = 642
    PLAYER_PK_VALUE_CHANGE_NOTIFY = 643
    REMOTE_PK_MODE_CHANGE_NOTIFY = 898
    REMOTE_PK_VALUE_CHANGE_NOTIFY = 899
